package main

import "fmt"
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

func main() {

	a:=1
	b:=1
	sum:=0
	for fib := 0 ;fib < 4000000; {
    fib = a+b
    a =b
    b =fib
    if fib% 2==0 {
            sum+=fib
    }

	}
	fmt.Println("sum: ",sum)
}
