//Author: Stephen Kinser
//problem 45
/****************************************************************************


NOT SOLVED
apparently T2872 is the next number, but won't show up as correct



*******************************************************************************/
/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

*/
#include<iostream>
bool isPentagonal(long long x){
	double n = (1 + sqrt((24 * x) + 1)) / 6;
	return n == trunc(n);
}
int main(){
	
	unsigned long long hexagonal = 0;
	//unsigned long long pentagonal=1;
	long answer = 0;
	long max = 100000000;
	//int j = 1;
	//bool flag = false;
	for (unsigned long long i = 144; i< max; i++){
		hexagonal = i*((2 * i) - 1);
		if (isPentagonal(hexagonal)){
			answer = hexagonal;
			break;
		}
	}
	
	std::cout << answer << '\n';
	return 0;
}
